---
title: "Wk5Prac"
output: html_document
date: "2022-11-02"
---

GOAL: join polygons of boroughs with number of hotels and airbnbs and hotels

##ONE: Load Libraries and Data

```{r setup, include=FALSE}
library(sf)
library(tmap)
library(tmaptools)
library(tidyverse)
library(here)
library(leafpop)
library(leaflet)
library(grid)
library(readr)
library(janitor)
library(dplyr)

airbnb <- read_csv(here("wk5_data","listings.csv"), locale = locale(encoding = "latin1"),
                       na = "NA")

Londonborough <- st_read(here::here("wk5_data","statistical-gis-boundaries-london", "ESRI", "London_Borough_Excluding_MHW.shp")) %>%
  st_transform(., 27700)

OSM <- st_read(here::here("wk5_data","greater-london-latest-free.shp", "gis_osm_pois_a_free_1.shp")) %>% 
  st_transform(.,27700) %>% 
  filter(fclass=='hotel')

Worldcities <- st_read(here::here("wk5_data", "World_Cities", "World_Cities.shp")) %>%
  st_transform(., 27700)

UK_outline <- st_read(here::here("wk5_data", "gadm36_GBR_shp", "gadm36_GBR_0.shp")) %>%
  st_transform(., 27700)

```

## R Markdown
Manipulate and Join Data
1. Spatial Join using st_join()

```{r cars}

join_example <- st_join(Londonborough, OSM)

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
